### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [myroslav-bakuta/JS-Carousel-JQuery#1]
Для jquery желательно другое именование переменных
![image](https://user-images.githubusercontent.com/8464662/79990579-e5f3d580-84b9-11ea-949a-fe4c87550b85.png)

делегирование для jquery реализовано неправильно
![image](https://user-images.githubusercontent.com/8464662/79990722-0d4aa280-84ba-11ea-8041-e24e84149ec0.png)

постоянное передергивать дом для доступа к элементам - очень плохая идея
![image](https://user-images.githubusercontent.com/8464662/79990788-25222680-84ba-11ea-8c55-7efb38a18bbd.png)

это нужно в конечной версии?
![image](https://user-images.githubusercontent.com/8464662/79990855-3bc87d80-84ba-11ea-88b4-aa4c935b0410.png)

**Comment by myroslav-bakuta** [comment]
https://github.com/myroslav-bakuta/JS-Carousel-JQuery/commit/e2a256a3eee94070114ff66e2e0dfccd438cc459
